name: Upstream Sync
permissions:
  contents: write
  issues: write
  actions: write
on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时触发一次
  workflow_dispatch:
jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - uses: actions/checkout@v4
      - name: Clean issue notice
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: '🚨 Sync Fail'
      - name: Sync upstream changes
        id: sync
        uses: jamesives/github-action-sync-fork@v4
        with:
          upstream_sync_repo: Dooy/chatgpt-web-midjourney-proxy
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 自动生成，无需手动设置
          test_mode: false
      - name: Sync check
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '🚨 同步失败 | Sync Fail'
          labels: '🚨 Sync Fail'
          body: |
            由于 [chatgpt-web-midjourney-proxy][upstream_repo] 上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，请查看 [详细教程][tutorial-zh-CN]
            Due to a change in the workflow file of the [chatgpt-web-midjourney-proxy][upstream_repo] upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the detailed [Tutorial][tutorial-en-US] for instructions.

